### ISSUE TITLE
How to use Canu in Circlator all?

### ISSUE THREAD

**Issue by caonetto** [sanger-pathogens/circlator#101]
I keep on getting an error (unrecognized arguments: --assembler) when I use
circlator all --assembler canu --merge_min_id 85 --merge_breaklen 1000 contigs.fasta  correctedReads.fasta.gz /mnt/output

Canu is in my path.

Any ideas?

**Comment by flass** [comment]
I am having the same issue trying to specify spades assembly. Weirdly, this is not an issu when run interactively, but it systematically fails when run as a cluster submission job.
Examples of error (with the command, as interpreted by the shell, echoed before execution):
```circlator all --assembler spades canu_assembly/D03_1/contigs.fasta canu_assembly/D03_1/correctedReads.fasta.gz circlator_postassembly/D03_1
usage: circlator all [options] <assembly.fasta> <reads.fasta/q> <output directory>
circlator: error: unrecognized arguments: --assembler circlator_postassembly/D03_1
```
or (after having run the first steps interactively, but having to end my session during the SPAdes assembly step):
```circlator assemble --assembler spades --threads 4 circlator_postassembly/D03_1/02.bam2reads.fasta circlator_postassembly/contigs/D03_1/03.assemble
usage: circlator assemble [options] <in.reads.fasta> <out_dir>
circlator: error: unrecognized arguments: --assembler circlator_postassembly/D03_1/03.assemble
```

**Comment by andrewjpage** [comment]
I'm afraid I cant replicate this error. I've used the --assembler parameter on a few hundred assemblies processed via a cluster (LSF).  My guess is that possibly there is an older version of the code being picked up somewhere which doesnt include this feature (its more recent), or the escaping of the command to the cluster didnt work quite right.
