### ISSUE TITLE
installing circlator

### ISSUE THREAD

**Issue by supanthee** [sanger-pathogens/circlator#102]
I think this is a trivial point that I am not being able to overcome. 

I am trying to install circlator. However, didn't succeed. I downloaded the release and tried to install like this, it says python3: command not found
Suresh-Panthees-MacBook-Pro:~ Suresh$ cd desktop
Suresh-Panthees-MacBook-Pro:desktop Suresh$ cd circlator-1.5.1
Suresh-Panthees-MacBook-Pro:circlator-1.5.1 Suresh$ python3 setup.py test
-bash: python3: command not found
Suresh-Panthees-MacBook-Pro:circlator-1.5.1 Suresh$ 

Help please

Thanks

Suresh

**Comment by andrewjpage** [comment]
Python3 is not setup correctly on your machine. I would recommend you contact your local system administrator for assistance.
