### ISSUE TITLE
how to use circlator on computer without internet access

### ISSUE THREAD

**Issue by EricDeveaud** [sanger-pathogens/circlator#108]
Hello, 

one of our users reported a problem with circlator. running on our cluster.

NB our compute node are on a private network and DOES NOT have access to internet.
get_dnaa was failing due to no net access.

is there a way to provide circlator an alternate method to get dnaa ? 
we already host this file on our data center and it can be accessed via plain file reading.

regards

Eric

**Comment by jnesme** [comment]
`circlator all --help ` returns this line:

```
fixstart options:
  --genes_fa FILENAME   FASTA file of genes to search for to use as start
                        point. If this option is not used, a built-in set of
                        dnaA genes is used
```
