### ISSUE TITLE
progcheck: found nucmer but couldn't get version

### ISSUE THREAD

**Issue by nataliering** [sanger-pathogens/circlator#110]
Hi

Having installed circlator using `pip3 install` then added it to my PATH, I tried `circlator progcheck`. All the dependencies are there except one: 
```
ubuntu@nat:~/Data/BP_UK36/gDNA/canu$ circlator progcheck
Circlator version: 1.5.1

External dependencies:
bwa     0.7.15  /home/ubuntu/biobuilds-2017.05/bin/bwa
canu    1.5     /home/ubuntu/biobuilds-2017.05/bin/canu
**Found nucmer but couldn't get version.**
prodigal        2.6.3   /home/ubuntu/biobuilds-2017.05/bin/prodigal
samtools        1.3.1   /home/ubuntu/biobuilds-2017.05/bin/samtools
WARNING: SPAdes version 3.10.1 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
spades  3.10.1  /home/ubuntu/biobuilds-2017.05/bin/spades.py

Python version:
3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]

Python dependencies:
openpyxl        2.4.8   /home/ubuntu/.local/lib/python3.5/site-packages/openpyxl/__init__.py
pyfastaq        3.15.0  /home/ubuntu/.local/lib/python3.5/site-packages/pyfastaq/__init__.py
pymummer        0.10.2  /home/ubuntu/.local/lib/python3.5/site-packages/pymummer/__init__.py
pysam   0.11.2.2        /home/ubuntu/.local/lib/python3.5/site-packages/pysam/__init__.py
```
Any ideas as to how can I fix this, please? Why would nucmer's version not be findable?

Thank you,
Nat

**Comment by nataliering** [comment]
Fixed! 

I was using a beta release of mummer, which had "beta" in the version number. `progcheck` looks for a response to `mummer --version` which only has numbers, so it was getting confused. I switched back to the latest alpha release, but that didn't work either because `--version` doesn't seem to work (bug with that mummer version I guess?) so I switched down to one release prior to the latest (3.9.3 alpha) and that one works!

**Comment by spock** [comment]
I have first tried replacing the version reported by nucmer (by using the latest 4.0.0beta1, and running `sed -i.bak 's/4\.0\.0beta1/4.0.0/' config.h configure` before configuring), but that failed.

Looking into the version-checking code of Circlator, we see that it is looking for a nucmer version string which matches this expression:
```
^NUCmer \(NUCleotide MUMmer\) version ([0-9\.]+)
```

So any of the 3.9+ versions would fail, as they simply print out the number without any text in front of it (e.g. `3.9.3alpha`).

I have edited the regular expression in my installation of circlator to read
```
'^([0-9\.]+.*)'
```
and that seems to have fixed the issue. I'm now using the latest mummer package, and I hope that there are no incompatibilities :) (I'm past the version check error, but circlator is still running so it may still fail at a stage where it actually uses nucmer.)

**Comment by samfux84** [comment]
Is it possible to change the regexp after installing circlator or does this fix require reinstallation ?

**Comment by spock** [comment]
I think I had no problems editing after installing (don't remember for sure), but any relevant and existing .pyc files may need to be deleted.

**Comment by samfux84** [comment]
@spock Thank you for your reply.

Do you remember which file has to be changed ?

**Comment by spock** [comment]
Yes, just looked for it - my `.local/lib/pythonX.Y/site-packages/circlator/external_progs.py`, and then clear the `__pycache__` directory.

**Comment by samfux84** [comment]
@spock Thank you very much.
