### ISSUE TITLE
Is circlator compatible with Python 2.7 ?

### ISSUE THREAD

**Issue by samfux84** [sanger-pathogens/circlator#116]
In the list of dependencies, you mention a lost of software, but you are not saying if circlator requires Python 3 or if it is also compatible with Python 2.7

Please add a statement to the dependencies about which Python version is required for circlator.

**Comment by samfux84** [comment]
Nobody ?

**Comment by samfux84** [comment]
You also forgot to mention a few more dependencies:

- openpyxl
- pyfastaq
- pymummer
- jdcal
- et_xmlfile

**Comment by andrewjpage** [comment]
Its Python 3 only. The installation instructions refer to 'pip3' and 'python3'.  There is no need to explicitly mention the dependencies above since they get automatically checked and installed in the standard manner.
