### ISSUE TITLE
nucmer version detected by "circlator progcheck" but not "circlator all"

### ISSUE THREAD

**Issue by MattPinder** [sanger-pathogens/circlator#122]
I have installed circlator on the Linux system at my workplace, and when running ``circlator progcheck`` most of the dependencies are fine (SPAdes gives the 'couldn't get version' message but I intend to use Canu so I guess this won't cause an issue?):

``Circlator version: 1.5.1``

``External dependencies:``
``bwa     0.7.15  /usr/local/packages/bwa-0.7.15/bwa``
``canu    1.3     /usr/local/packages/canu-1.3/Linux-amd64/bin/canu``
**``nucmer  3.1     /usr/local/packages/MUMmer3.23/nucmer``**
``prodigal        2.6.3   /usr/local/packages/Prodigal_v2.6.3/prodigal``
``samtools        1.5     /usr/local/packages/anaconda3-4.4.0/bin/samtools``
``Found spades but couldn't get version.``

``Python version:``
``3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58)``
``[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]``

``Python dependencies:``
``openpyxl        2.4.7   /usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/openpyxl/__init__.py``
``pyfastaq        3.16.0  /usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/pyfastaq-3.16.0-py3.6.egg/pyfastaq/__init__.py``
``pymummer        0.10.3  /usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/pymummer-0.10.3-py3.6.egg/pymummer/__init__.py``
``pysam   0.11.2.2        `/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/pysam/__init__.py``

However, upon attempting to run ``circlator all``, it can't find a version number for nucmer, and thus the job fails:

``Traceback (most recent call last):``
``  File "/usr/local/packages/anaconda3-4.4.0/bin/circlator", line 4, in <module>``
    ``__import__('pkg_resources').run_script('circlator==1.5.1', 'circlator')``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script``
``  File "/home/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.1-py3.6.egg/EGG-INFO/scripts/circlator", line 58, in <module>``
``    exec('circlator.tasks.' + task + '.run()')``
``  File "<string>", line 1, in <module>``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.1-py3.6.egg/circlator/tasks/all.py", line 74, in run``
``    circlator.versions.get_all_versions(None, raise_error=True, assembler=options.assembler)``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.1-py3.6.egg/circlator/versions.py", line 15, in get_all_versions``
``    external_progs.check_all_progs(verbose=False, raise_error=raise_error, filehandle=filehandle, debug=debug, assembler=assembler)``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.1-py3.6.egg/circlator/external_progs.py", line 108, in check_all_progs``
``    make_and_check_prog(prog, verbose=verbose, raise_error=raise_error, filehandle=filehandle, debug=debug, required=prog==assembler)``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.1-py3.6.egg/circlator/external_progs.py", line 81, in make_and_check_prog``
``    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)``
``  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.1-py3.6.egg/circlator/external_progs.py", line 56, in handle_error``
``    raise Error(message + '\nCannot continue')``
``circlator.external_progs.Error: Found nucmer but couldn't get version.``
``Cannot continue``

I'm unsure how to get circlator to see the correct version of nucmer, especially as ``circlator progcheck`` **can** see the version number, so any guidance would be appreciated.
Many thanks.

**Comment by andrewjpage** [comment]
Hi,
There is a fix in version 1.5.3 which we are pushing now to pypi (will take a few hours).  In the interim you can install the latest version directly from github.
Andrew

**Comment by MattPinder** [comment]
I just installed version 1.5.3 from the ``.tar.gz`` file at https://github.com/sanger-pathogens/circlator/releases, but this is giving me the exact same problem as with version 1.5.1; the only difference in the error log is the circlator version number

**Comment by andrewjpage** [comment]
I hopefully have corrected the issue this time in v1.5.4 and have added tests for any nucmer version strings I could find (plus for other dependancies). It will take a few hours before it appears on pypi.
