### ISSUE TITLE
Infinite recursion in clean.py ?

### ISSUE THREAD

**Issue by aWormGuy** [sanger-pathogens/circlator#123]
Hi,
I installed `circlator` version 1.5.2 via bioconda, tried running the entire circlator pipeline using: 

`circlator all $POLISHED_ASSEMBLY $PRE_ASSEMBLED_READS $OUTPUT_DIR;`

I am getting the following error:

`Traceback (most recent call last):`
`  File "/myhomefolder/anaconda3/lib/python3.6/site-packages/circlator/clean.py", line 145, in _get_all_containing`
`    new_names = self._get_all_containing(containing_contigs, containing_contig, exclude=name)`
`  File "/myhomefolder/anaconda3/lib/python3.6/site-packages/circlator/clean.py", line 145, in _get_all_containing`
`    new_names = self._get_all_containing(containing_contigs, containing_contig, exclude=name)`
`  File "/myhomefolder/anaconda3/lib/python3.6/site-packages/circlator/clean.py", line 145, in _get_all_containing`
`    new_names = self._get_all_containing(containing_contigs, containing_contig, exclude=name)
  [Previous line repeated 995 more times]`
`  File "/myhomefolder/anaconda3/lib/python3.6/site-packages/circlator/clean.py", line 138, in _get_all_containing`
`    contains_name = set()`
`RecursionError: maximum recursion depth exceeded while calling a Python object`

I get the same error even after I tried increasing the recursion depth using the following :

`import sys`
`sys.setrecursionlimit(10000)`

Any tips on how to avoid this?

Thanks,
-Amit.

**Comment by andrewjpage** [comment]
I've updated the code to fix this bug. Please update to version 1.5.5. Thanks for reporting it.
