### ISSUE TITLE
Problems running progcheck, error with installation?

### ISSUE THREAD

**Issue by caonetto** [sanger-pathogens/circlator#124]
I installed circlator and I know some dependencies are missing, but I wanted to do a progcheck and It wont work. Does this mine there is a problem with the installation?

`ubuntu@biolinux:~$ '/mnt/circlator-1.5.3/scripts/circlator' all
Traceback (most recent call last):
  File "/mnt/circlator-1.5.3/scripts/circlator", line 57, in <module>
    exec('import circlator.tasks.' + task)
  File "<string>", line 1, in <module>
ImportError: No module named 'circlator'`

**Comment by andrewjpage** [comment]
Yes this is a problem with your installation. It looks like your python setup is not finding the python modules correctly.  Your local IT support are best placed to assist you with this.
