### ISSUE TITLE
Java requirement error in java

### ISSUE THREAD

**Issue by conchoecia** [sanger-pathogens/circlator#140]
In the docker version of circlator, `--assembler canu` crashes with the following error

```
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from 'java').
ERROR:  'java -showversion' reports:
```

**Comment by kimnegrette3** [comment]
Hi! did you get past this error? I just got the same message while running circlator in the docker. 
Thanks!

**Comment by cwarden45** [comment]
I am also getting the same error when trying to use Circlator for analysis of Canu assembly and corrected reads data (through the Docker image).

**Comment by Lfulcrum** [comment]
This should be fixed in the [latest release](https://github.com/sanger-pathogens/circlator/releases/latest) (v1.5.5-docker5).
