### ISSUE TITLE
--spades_k  error when using all

### ISSUE THREAD

**Issue by nblouin** [sanger-pathogens/circlator#146]
Hi there
New to Circlator.
If I run _circlator assemble --spades_k 21,33,45_ ... all is well.
However when I try the same in _all_, I get an error. 
I am afraid I might misunderstand running all rather than Circlator individual steps.
Any help would be appreciated:

┌─[15:34:03]─[✗:1]─[nblouin@thm05]─[/project/bishalab/nblouin/CirclatorClosedGenomes]
└──> circlator all --verbose --spades_k 21,33,45 1017_genome_final_HGAP3.fasta RawReads/lane8-s065-indexN708-S517-CAGAGAGG-GCGTAAGA-1017_S65_L008_R1_001.fastq.gz 1017

usage: circlator all [options] <assembly.fasta> <reads.fasta/q> <output directory>
circlator: error: unrecognized arguments: --spades_k 1017

**Comment by RoyChaudhuri** [comment]
For all, that option is called --assemble_spades_k not --spades_k
