### ISSUE TITLE
circlator progcheck report PATH of binary?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/circlator#36]
Martin - could you modify circlator to print out *which* binary it found?
eg.

```
% circlator  progcheck
Using bwa version 0.7.12 as /bio/sw/bwa/bin/bwa
Using samtools version 1.2 as /usr/bin/samtools
```

**Comment by martinghunt** [comment]
Hi Torsten,

Good idea. It's now implemented in the latest version (1.0.1).

Martin
