### ISSUE TITLE
contig.fastg went missing because of SPAdes 3.6.1 output changes

### ISSUE THREAD

**Issue by cschaef78** [sanger-pathogens/circlator#39]
Hi,

circlator is crashing because contigs.fastg went missing because in SPAdes 3.6.1 contigs.fastg files are not supported anymore (See below changelog SPAdes 3.6,1). Could you please look into this. 

Traceback (most recent call last):
  File "/.linuxbrew/opt/python3/lib/python3.5/site-packages/pyfastaq/utils.py", line 21, in open_file_read
    f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '03.assemble/contigs.fastg'

"SPAdes Genome Assembler changelog
SPAdes 3.6.1, 4 October 2015

CHANGE: No misleading FASTG files, only assembly graph is saved in FASTG format. "

Thank you in advance,
Best regards,
Christian

**Comment by martinghunt** [comment]
Hi Christian,

Thanks for reporting this. It will take some time to look into, as we had reasons for using the contigs.fastg file instead of scaffolds.fastg. We'll need to test SPAdes 3.6.1 before making changes to the circlator code.

In the meantime, could you use SPAdes 3.5.0 or 3.6.0? It might help to know that you can use the environment variable $CIRCLATOR_SPADES to tell Circlator the name of the spades.py executable you want it to use.

Best,
Martin

**Comment by cschaef78** [comment]
Hi Martin,

Thanks for your quick response. I have also taken into consideration to use a previous version of SPAdes but since they are not available for download anymore it is a little bit trickier than usual.

Thanks again for looking into this problem.

Best regards,
Christian

**Comment by martinghunt** [comment]
Hi Christian,

I hadn't realised that the old versions of SPAdes are not linked from their website.

However, changing the version number in the download link works for me. eg:
wget http://spades.bioinf.spbau.ru/release3.5.0/SPAdes-3.5.0-Linux.tar.gz

Best,
Martin

**Comment by cschaef78** [comment]
Hi Martin,

Thanks for your response and your solution via wget. In the meantime I received previous versions of SPAdes from the developing team. With these previous versions of SPAdes circlator works as expected.
Thanks again for your help and for looking into this issue.

Best,
Christian

**Comment by martinghunt** [comment]
Hi Christian,

The graph information is now output by the latest SPAdes version 3.6.2.

Circlator has been updated to use SPAdes 3.6.2, and still works with versions before 3.6.1. Circlator will no longer work with with 3.6.1.

Best,
Martin

**Comment by cschaef78** [comment]
Hi Martin,

Thank you very much for the updated version of circlator.
Best,
Christian
