### ISSUE TITLE
disabling mismatch correction in SPAdes

### ISSUE THREAD

**Issue by gedankenstuecke** [sanger-pathogens/circlator#51]
I'm running *circlator* with *SPAdes 3.6.0* and sometimes it crashes with the following error during the contig mismatch correction at the end: 

```
Line 6191, sequence length 17974 vs 1590 from CIGAR
Parse error at line 6191: CIGAR and sequence length are inconsistent


== Error ==  system call for: "['/home/bastian/bin/SPAdes-3.5.0-Linux/bin/corrector', '/share/project/circlator_results/03.assemble.tmp.spades.87.7bjtc3gr/mismatch_corrector/contigs/configs/corrector.info', '/share/project/circlator_results/03.assemble.tmp.spades.87.7bjtc3gr/misc/assembled_contigs.fasta']" finished abnormally, err code: -6
```

This leads to the whole `circlator all` crashing in the end, as it happens for each k-mer size. I guess I could just hard-code the corresponding flags into circlator, but I wondered whether disabling this would  

a) be a good idea at all or whether it will lead to my results going down the drain
b) if this should be added as a general option to *circlator* if it's a good idea?

**Comment by martinghunt** [comment]
I have always used spades with --careful (I guess this is the option you want to remove?), so don't know what the effect would be. I suspect that it won't have much effect on Circlataor itself. From the description in the spades help, I guess the percent identity between the spades reassembly and the original contigs could potentially drop a tiny bit. You could compenstate by lowering the minimum identity with --merge_min_id.

I think it's definitely a good idea to add a circlator option to change it.

**Comment by gedankenstuecke** [comment]
Yes, `--careful` is the option I want to remove as it takes lots of time and at least in some versions of *SPAdes* it crashes depending on the circumstances. 

So, I will try adding this in a branch and do a PR. And then we can also see whether it makes a huge difference :smiley:

**Comment by martinghunt** [comment]
I'm already doing it. Probably easier for me as there are a few places where things need to be changed.

**Comment by gedankenstuecke** [comment]
Oh, okay. I'm already halfway there as well now. :joy:

**Comment by gedankenstuecke** [comment]
Closed I'd say. I also updated the wiki-pages to reflect the new parameters :smiley:
