### ISSUE TITLE
circlator fails and still creates the final output file 06.fixstart.fasta

### ISSUE THREAD

**Issue by afif-elghraoui** [sanger-pathogens/circlator#55]
I've been testing circlator for use in an automated de novo assembly pipeline and see that it doesn't always work. Furthermore, it doesn't error out when something goes wrong, so my pipeline proceeds with assembly polishing despite the circularization not having been performed. Here are the logs for one failed sample:

```
==> 02.bam2reads.log <==
[bamfilter]     #contig length  reads_kept
[bamfilter]     scf7180000000004|quiver 4449764 1-50000;4399765-4449764

==> 04.merge.circularise_details.log <==
[merge circularise_details]     scf7180000000004|quiver Checking 3 nucmer hits
[merge circularise_details]     scf7180000000004|quiver potential pair of nucmer hits for circularization:
[merge circularise_details]     scf7180000000004|quiver         1       36542   36552   1       36542   36552   99.94   4449764 58223   1       scf7180000000004|quiver NODE_1_length_58223_cov_29.3807_ID_823
[merge circularise_details]     scf7180000000004|quiver         4406770 4440158 55874   22486   33389   33389   99.99   4449764 58223   1       scf7180000000004|quiver NODE_1_length_58223_cov_29.3807_ID_823
[merge circularise_details]     scf7180000000004|quiver cannot use this pair because positions/orientations of matches no good
[merge circularise_details]
[merge circularise_details]     SPAdes reassembly contigs that are circular: None
[merge circularise_details]
[merge circularise_details]     scf7180000000004|quiver Trying to circularize. Has nucmer hits to check...
[merge circularise_details]     scf7180000000004|quiver No matches to SPAdes circular contigs

==> 04.merge.circularise.log <==
[merge circularised]    #Contig repetitive_deleted      circl_using_nucmer      circl_using_spades      circularised
[merge circularised]    scf7180000000004|quiver 0       0       0       0

==> 04.merge.merge.iterations.log <==
[merge iterative_merge 1]       Using nucmer matches from 04.merge.merge.iter.1.coords
[merge iterative_merge 1]       You can view the nucmer matches with ACT using: ./04.merge.merge.iter.1.start_act.sh
[merge iterative_merge 1]       NODE_1_length_58223_cov_29.3807_ID_823: checking nucmer matches
[merge iterative_merge 1]       NODE_1_length_58223_cov_29.3807_ID_823: no potential pairs of hits to merge contigs
[merge iterative_merge 1]       Potential contigs to use for merging: 
[merge iterative_merge 1]       Contigs to use for merging after uniqueness filtering: 
[merge iterative_merge 1]       Made at least one contig join: False
[merge iterative_merge 1]       No contig merges were made

==> 05.clean.log <==
[clean] scf7180000000004|quiver kept

==> 06.fixstart.log <==
[fixstart]      id      break_point     gene_name       gene_reversed   new_name        skipped
[fixstart]      scf7180000000004|quiver -       -       -       -       skipped
```

It seems that the correct match was found, but circlator refused to use it. I ended up doing manual trimming and using minimus2 for this sample (This sample has a heterogeneous IS element insertion which caused this problem). I could work around this by adding code to my pipeline to check if the output file is the same as the input, but I think you should be aware of this problem. I was especially hoping that circlator would automatically resolve these troublesome cases.

Many thanks for this software.

**Comment by martinghunt** [comment]
Thanks for you feedback. I think Circlator should return a zero when nothing actually crashed. As an analogy, should a read mapper return nonzero if it made a valid bam file of unmapped reads?

Re that pair of matches - they are too far away from the ends of the contigs, so Circlator rejected them. The matches were ~22kb from the end of the reassembled contig and the start of the input contig. 

You can change the defaults with:
  --merge_ref_end INT   max distance allowed between nucmer hit and end of
                        input assembly contig [15000]
  --merge_reassemble_end INT
                        max distance allowed between nucmer hit and end of
                        reassembly contig [1000]

Those options can be increased, at the potential cost of making errors. By default Circlator is set to be conservative.

**Comment by afif-elghraoui** [comment]
On Mon, Apr 18, 2016 at 12:56 AM, martinghunt <notifications@github.com>
wrote:

> I think Circlator should return a zero when nothing actually crashed. As
> an analogy, should a read mapper return nonzero if it made a valid bam file
> of unmapped reads?
>
Yes, because it clearly didn't achieve what was requested of it and the
resulting bam file is pretty much useless.
Similarly, `grep` has exit status 1 if no match is found.
Right now, there's absolutely no explicit indication of whether a run was
successful-- even in verbose mode-- without checking the logs for each run
or testing whether the output file is 100% identical to the input.

Re that pair of matches - they are too far away from the ends of the
> contigs, so Circlator rejected them. The matches were ~22kb from the end of
> the reassembled contig and the start of the input contig.
>

For my own reference, from what I remember of mummer's show-coords output
and using some inference here, the headers for the first few columns are

seq1-match-start, seq1-match-end, seq2-match-start, seq2-match-end,
seq1-match-length, seq2-match-length, %-identity, seq1-length, seq2-length

I'm not sure that I understand. It looks like input:1-36542 matched with
reassembled:36552-1 and that input:4406770-4440158 matched
reassembled:55874-22486.
If you're referring to the 22486 matching the end of the input contig, I
have another sample with a successful circlator run that has a much bigger
discrepancy than 1 to 22486 for this distance,
so I guess I don't understand what you mean by the distance from the end of
the reassembled contig to the start of the input contig.

You can change the defaults with:
> --merge_ref_end INT max distance allowed between nucmer hit and end of
> input assembly contig [15000]
> --merge_reassemble_end INT
> max distance allowed between nucmer hit and end of
> reassembly contig [1000]
>

>
Those options can be increased, at the potential cost of making errors. By
> default Circlator is set to be conservative.
>
Thanks for the tip. While I can play around with the parameters, I filed
this ticket mostly because of the non-reporting of failure.

**Comment by martinghunt** [comment]
I see your point, but I guess we'll have to agree to disagree on the error code then :) In our pipeline we want to continue even if no circularizations were made.
How about an option to 'circlator all' that returns nonzero when nothing was circularized? 

Sorry, I misread the nucmer matches initially. It's just the distance to the end of the reassembled (spades) contigs that failed the cutoff for the second match. 55874-22486 is more than 1kb from the end fo the contig (58223 long). While we wre testing circlator, we found that making this more than 1kb often resulted in incorrect circularisations, so decided to be more conservative at the cost of missing the odd join. Hopefully this picture helps (coords in kb)...

![img_20160419_082707](https://cloud.githubusercontent.com/assets/4937411/14630945/b8f9ed14-0608-11e6-9830-179c9388b1f7.jpg)

(and the matches at the starts are both at 1, which obviously passes the 1kb and 15kb cutoffs)
.

**Comment by afif-elghraoui** [comment]
[Looks like my previous post got mangled with quoting you -- Sorry about
that;  I'm using a better mail client now that hopefully will not have
this issue]

على الثلاثاء 19 نيسـان 2016 ‫00:31، كتب martinghunt:
> I see your point, but I guess we'll have to agree to disagree on the
> error code then :) In our pipeline we want to continue even if no
> circularizations were made.

Fair enough. Regardless of the exit status, though, I think there should
also be a brief summary (like "M of N contigs were circularized")
reported in verbose mode. It looks like you've added something to this
extent in a recent commit already.

> How about an option to 'circlator all' that returns nonzero when nothing
> was circularized?
>

That sounds great and would be useful to me.

> Sorry, I misread the nucmer matches initially. It's just the distance to
> the end of the reassembled (spades) contigs that failed the cutoff for
> the second match. 55874-22486 is more than 1kb from the end fo the
> contig (58223 long). While we wre testing circlator, we found that
> making this more than 1kb often resulted in incorrect circularisations,
> so decided to be more conservative at the cost of missing the odd join.
> Hopefully this picture helps (coords in kb)...
> 

I had drawn the same diagram after your first message! Yes, it makes
sense now with your explanation. Many thanks for making it clear.

**Comment by martinghunt** [comment]
(I think github is mangling! It's fine in my email)

I just made a new release 1.2.1 that:
1. has a new option --unchanged_code to have a return code of your choice when the input contigs == output contigs (default is zero)
2. When verbose, prints a summary like this at the end:

    ___________________________________ Summary ___________________________________
    Number of input contigs: 3
    Number of contigs after merging: 2
    Circularized 1 of 2 contig(s)

**Comment by afif-elghraoui** [comment]
Very nice. Many thanks!
