### ISSUE TITLE
Add --verbose to the other subcommands

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/circlator#57]
When I run commands like 
```
circlator fixstart --genes_fa dnaA.aa.fa pilon.fasta pilon.fixstart
```
it prints absolutely nothing.

This makes me think something is wrong and induces CTRL-C anxiety, only to be presented with a Python backtrace :-)

I can see it is calling `syscall.run('bash ' + script, verbose=self.verbose)` but I am not able to set the verbosity from the command line.

**Comment by martinghunt** [comment]
Good point. I'll go through the commands and make each has a verbose option...

**Comment by martinghunt** [comment]
bam2reads and fixstart didn't have --verbose option. I've added --verbose to bam2reads, but not for fixstart. The reason being that it actually runs code from a separate package (bio_assembly_refiniment). Sometime soon the fixstart code is going to be refactored to remove the dependency on bio_assembly_refiniment, at which point I'll add a verbose option.

**Comment by martinghunt** [comment]
Fixed in version 1.2.1 (except fixstart, which will happed in the future).

**Comment by tseemann** [comment]
This is the future calling :-P

**Comment by martinghunt** [comment]
--verbose added to fixstart in release 1.3.0
