### ISSUE TITLE
Temporary folders not cleaned up when process killed

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/circlator#58]
Does the temp directory class in Python have a way to ensure cleanup in the case of killed job (eg. CTRL-C). Can you trap the signal?

eg. `pilon.fixstart.tmp.circlator.fixstart.xn4xwx51/`

**Comment by martinghunt** [comment]
It leaves it up to the user to cleanup. If it crashed then I want to know why and that usually means having a look at what's in the temp directory. So sorry, but I don't really want to change this.
