### ISSUE TITLE
fixstart fails if spaces in sequence names

### ISSUE THREAD

**Issue by martinghunt** [sanger-pathogens/circlator#64]
Also check other individual tasks. Running "circlator all" is ok because the first thing it does is fix the names in the input assembly.

**Comment by tseemann** [comment]
Any chance you'll fix this?

I am manually removing the FASTA `desc` for `circlator fix_start` to work.

**Comment by martinghunt** [comment]
I'll work on it over the next week or so. Thanks for the message from the future :) I'll add in a verbose option as well.

**Comment by martinghunt** [comment]
Fixed for fixstart in the new release 1.3.0. The output headers are the same as the input as well, ie descriptions don't get lost.

**Comment by tseemann** [comment]
Awesome!
