### ISSUE TITLE
minimus2 using hard-coded /usr/local/bin/show-coords 

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/circlator#65]
```
Command: /usr/local/bin/show-coords -H -c -l -o -r -I 94 /home/tseemann/tasks/glen.carter/canu_bad_pacbio/A01/pilon/tig00000000_pilon.seq.minimus2.merge/minimus2.delta | /bio/linuxbrew/Cellar/amos/3.1.0/bin/nucmerAnnotate | egrep 'BEGIN|END|CONTAIN|IDENTITY' > /home/tseemann/tasks/glen.carter/canu_bad_pacbio/A01/pilon/tig00000000_pilon.seq.minimus2.merge/minimus2.coords  exited with status: 1

... end of Minimus2 output.
```

```
% circlator progcheck
Using bwa version 0.7.13 as /bio/linuxbrew/bin/bwa
Using nucmer version 3.1 as /bio/linuxbrew/bin/nucmer
Using prodigal version 2.6.2 as /bio/linuxbrew/bin/prodigal
Using samtools version 1.3 as /bio/linuxbrew/bin/samtools
Using spades version .8.0 as /bio/linuxbrew/bin/spades.py
```

**Comment by tseemann** [comment]
I made sure I was up to date with 1.2.1 but same problem:

```
Circlator version: 1.2.1

External dependencies:
bwa     0.7.13  /bio/linuxbrew/bin/bwa
nucmer  3.1     /bio/linuxbrew/bin/nucmer
prodigal        2.6.2   /bio/linuxbrew/bin/prodigal
samtools        1.3     /bio/linuxbrew/bin/samtools
spades  3.8.0   /bio/linuxbrew/bin/spades.py

Python version:
3.5.1 (default, Mar 28 2016, 11:15:44)
[GCC 5.3.0]

Python dependencies:
bio_assembly_refinement 0.5.1   /bio/linuxbrew/opt/python3/lib/python3.5/site-packages/bio_assembly_refinement/__init__.py
openpyxl        2.3.5   /bio/linuxbrew/opt/python3/lib/python3.5/site-packages/openpyxl/__init__.py
pyfastaq        3.12.1  /bio/linuxbrew/opt/python3/lib/python3.5/site-packages/pyfastaq/__init__.py
pymummer        0.7.1   /bio/linuxbrew/opt/python3/lib/python3.5/site-packages/pymummer/__init__.py
pysam   0.8.3   /bio/linuxbrew/opt/python3/lib/python3.5/site-packages/pysam/__init__.py
```

**Comment by tseemann** [comment]
I now realise it is the fault of AMOS where `minimus2` is installed. It has `/usr/local` hard-coded everywhere!

Not sure if this is a `brew` installer issue or something else.

Argh.

**Comment by martinghunt** [comment]
Hi Torsten,

Yes, it's an AMOS installation issue. I was writing this reply when you closed it. I'll put it here anyway, in case anyone else gets the same problem...


I think this is a problem with your amos/minimus2 install. Take a look at lines 44-47 of the minimus2 script.

show-coords isn't explicitly called anywhere in the minimus2 bit of the circlator code. I think you can set them when running configure (see configure --help), or (the hacky solution) manually change them in the minimus2 script afterwards.

**Comment by tseemann** [comment]
Here's the bug: https://github.com/Homebrew/homebrew-science/issues/3707

**Comment by alexiswl** [comment]
I also had this issue when installing in a conda python=3.5 environment.
My solution was to change the code in ${CONDA_PREFIX}/bin/minimus2 for both SHOWCOORDS and DELTAFILTER
Interestingly the two variables have also been hard coded, but fortunately using the ${CONDA_PREFIX} variable.

**Comment by alexiswl** [comment]
I also had this issue when installing in a conda python=3.5 environment.
My solution was to change the code in ${CONDA_PREFIX}/bin/minimus2 for both SHOWCOORDS and DELTAFILTER
Interestingly the two variables have also been hard coded, but fortunately using the ${CONDA_PREFIX} variable.

Running the following line fixed the code whilst inside the environment.

sed -i 's%/usr/local%${CONDA_PREFIX}%g' ${CONDA_PREFIX}/bin/minimus2
