### ISSUE TITLE
Spades version detection error

### ISSUE THREAD

**Issue by uranus2001** [sanger-pathogens/circlator#67]
I just installed Circlator version: 1.2.1 using pip3 on my mac (OS X El Captain) after installing all the dependencies in the correct versions (I believe), but when I run progcheck, it gives me an error: Found spades but couldn't get version.  Any suggestions to solve this issue?  Thanks!

Below is the output when I type in "circlator progcheck".

Circlator version: 1.2.1

External dependencies:
bwa	0.7.15	xxxxxx
nucmer	3.1	xxxxxx
prodigal	2.6.3	xxxxxx
samtools	1.3.1	xxxxxx
Found spades but couldn't get version.

Python version:
3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Python dependencies:
bio_assembly_refinement	0.5.1	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bio_assembly_refinement/__init__.py
openpyxl	2.3.5	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/openpyxl/__init__.py
pyfastaq	3.12.1	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyfastaq/__init__.py
pymummer	0.7.1	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymummer/__init__.py
pysam	0.8.3	/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysam/__init__.py

**Comment by martinghunt** [comment]
What version of spades do you have installed? I haven't tested circlator with the newest versions. It definitely works with spades 3.6.0.

**Comment by uranus2001** [comment]
I tried all 3.5.0 / 3.6.0 / 3.6.2, but none of them was detected by Circlator.  I tested Spades itself, and it is working okay.

**Comment by martinghunt** [comment]
Does

    python2 spades.py

work?

**Comment by uranus2001** [comment]
It seems not working.  This is what I got. 

File "/xxxxxxx/SPAdes-3.6.0-Darwin/bin/spades", line 1
SyntaxError: Non-ASCII character '\xcf' in file /xxxxxxx/SPAdes-3.6.0-Darwin/bin/spades on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by martinghunt** [comment]
Can you paste the output of

    python2 `which spades.py`

**Comment by uranus2001** [comment]
xxxxxx:~ jungh$ which spades.py
(Return)
/xxxxxx/TIS/SPAdes-3.6.0-Darwin/bin/spades.py

I tried two different mac (OS X 10.9.5 & 10.11.4) computers without success (the same Spades version detection problem), but it worked okay with BioLinux computers in the lab.  So, now I guess this might relate to platforms??

**Comment by martinghunt** [comment]
Could you confirm what the output is of the complete command

    python2 `which spades.py`

on your mac? We tested it here on OSX 10.11.6 and it worked. Also, how are you installing spades?

**Comment by uranus2001** [comment]
I believe I got SPAdes binaries for Mac though curl and for linux through wget.
curl http://spades.bioinf.spbau.ru/release3.6.0/SPAdes-3.6.0-Darwin.tar.gz -o SPAdes-3.6.0-Darwin.tar.gz
wget http://spades.bioinf.spbau.ru/release3.6.0/SPAdes-3.6.0-Linux.tar.gz

Here is the output of the complete command.  Thanks!

xxxxxx:~ jungh$ python2 `which spades.py`
-bash: python2: command not found
xxxxxx:~ jungh$ python `which spades.py`
SPAdes genome assembler v.3.6.0

Usage: /xxxxxx/TIS/SPAdes-3.6.0-Darwin/bin/spades.py [options] -o <output_dir>

Basic options:
-o	<output_dir>	directory to store all the resulting files (required)
--sc			this flag is required for MDA (single-cell) data
--iontorrent		this flag is required for IonTorrent data
--test			runs SPAdes on toy dataset
-h/--help		prints this usage message

Input data:
--12	<filename>	file with interlaced forward and reverse paired-end reads
-1	<filename>	file with forward paired-end reads
-2	<filename>	file with reverse paired-end reads
-s	<filename>	file with unpaired reads
--pe<#>-12	<filename>	file with interlaced reads for paired-end library number <#> (<#> = 1,2,3,4,5)
--pe<#>-1	<filename>	file with forward reads for paired-end library number <#> (<#> = 1,2,3,4,5)
--pe<#>-2	<filename>	file with reverse reads for paired-end library number <#> (<#> = 1,2,3,4,5)
--pe<#>-s	<filename>	file with unpaired reads for paired-end library number <#> (<#> = 1,2,3,4,5)
--pe<#>-<or>	orientation of reads for paired-end library number <#> (<#> = 1,2,3,4,5; <or> = fr, rf, ff)
--s<#>		<filename>	file with unpaired reads for single reads library number <#> (<#> = 1,2,3,4,5)
--mp<#>-12	<filename>	file with interlaced reads for mate-pair library number <#> (<#> = 1,2,3,4,5)
--mp<#>-1	<filename>	file with forward reads for mate-pair library number <#> (<#> = 1,2,3,4,5)
--mp<#>-2	<filename>	file with reverse reads for mate-pair library number <#> (<#> = 1,2,3,4,5)
--mp<#>-s	<filename>	file with unpaired reads for mate-pair library number <#> (<#> = 1,2,3,4,5)
--mp<#>-<or>	orientation of reads for mate-pair library number <#> (<#> = 1,2,3,4,5; <or> = fr, rf, ff)
--hqmp<#>-12	<filename>	file with interlaced reads for high-quality mate-pair library number <#> (<#> = 1,2,3,4,5)
--hqmp<#>-1	<filename>	file with forward reads for high-quality mate-pair library number <#> (<#> = 1,2,3,4,5)
--hqmp<#>-2	<filename>	file with reverse reads for high-quality mate-pair library number <#> (<#> = 1,2,3,4,5)
--hqmp<#>-s	<filename>	file with unpaired reads for high-quality mate-pair library number <#> (<#> = 1,2,3,4,5)
--hqmp<#>-<or>	orientation of reads for high-quality mate-pair library number <#> (<#> = 1,2,3,4,5; <or> = fr, rf, ff)
--nxmate<#>-1	<filename>	file with forward reads for Lucigen NxMate library number <#> (<#> = 1,2,3,4,5)
--nxmate<#>-2	<filename>	file with reverse reads for Lucigen NxMate library number <#> (<#> = 1,2,3,4,5)
--sanger	<filename>	file with Sanger reads
--pacbio	<filename>	file with PacBio reads
--nanopore	<filename>	file with Nanopore reads
--trusted-contigs	<filename>	file with trusted contigs
--untrusted-contigs	<filename>	file with untrusted contigs

Pipeline options:
--only-error-correction	runs only read error correction (without assembling)
--only-assembler	runs only assembling (without read error correction)
--careful		tries to reduce number of mismatches and short indels
--continue		continue run from the last available check-point
--restart-from	<cp>	restart run with updated options and from the specified check-point ('ec', 'as', 'k<int>', 'mc')
--disable-gzip-output	forces error correction not to compress the corrected reads
--disable-rr		disables repeat resolution stage of assembling

Advanced options:
--dataset	<filename>	file with dataset description in YAML format
-t/--threads	<int>		number of threads
				[default: 16]
-m/--memory	<int>		RAM limit for SPAdes in Gb (terminates if exceeded)
				[default: 250]
--tmp-dir	<dirname>	directory for temporary files
				[default: <output_dir>/tmp]
-k		<int,int,...>	comma-separated list of k-mer sizes (must be odd and
				less than 128) [default: 'auto']
--cov-cutoff	<float>		coverage cutoff value (a positive float number, or 'auto', or 'off') [default: 'off']
--phred-offset	<33 or 64>	PHRED quality offset in the input reads (33 or 64)
				[default: auto-detect]

**Comment by martinghunt** [comment]
OK, so it looks like the issue is that circlator assumes that the command "python2" is in your path. I'll fix this in the next week or two and do a new release of circlator. For now, you could symlink python2 to point to python.

**Comment by uranus2001** [comment]
Thanks a lot for all the kind helps!  Now the circlator recognizes spades version and works great on my mac!!
