### ISSUE TITLE
SPAdes 3.7.1 recommendation

### ISSUE THREAD

**Issue by sjackman** [sanger-pathogens/circlator#72]
> WARNING: SPAdes version 3.9.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.

Do you have any thoughts as to why SPAdes 3.7.1 performs better than 3.9.0 with Circlator?
cc Anton Korobeynikov @asl 

@ilovezfs and I maintain the `circlator` package for Homebrew/Science, and we'd prefer to use SPAdes 3.9.0 with Circlator if possible.

**Comment by martinghunt** [comment]
If it's a pain, go with 3.9.0.

I tested all versions from 3.6.2-3.9.0 on the 14 NCTC samples from the Circlator paper. SPAdes 3.7.x resulted in the most circularizations. The differences were mostly in the samples with several plasmids. But the differences were in the SPAdes reassembly of contig ends, not SPAdes itself assembling the plasmids and calling them as circular. Don't know any more than that. I just looked at the final counts of number of circularizations, haven't dug into the details of the reassemblies and what was different about them. Unlikely I'll get the time to.

That said, I wouldn't be surprised if a different dataset gave different results anyway, as assembly can be so variable. So I'm ok with 3.9.0 in homebrew. The same thing will happen with debian packaging anyway.

**Comment by sjackman** [comment]
Great. Thanks for your quick response, Martin.

**Comment by asl** [comment]
The results should be pretty much the same. The major differences were in metaSPAdes, plasmidSPAdes and rnaSPAdes pipelines and almost nothing was changed for normal isolate assemblies besides several bug fixes in the repeat resolution. So, it may happen that SPAdes 3.7 indeed did unsafe decisions (probably even introducing misassemblies), however, providing longer contigs.

**Comment by martinghunt** [comment]
Interesting. Thanks for the info @asl. It's probably the bug fixes in repeat resolution that made the difference. Circlator is only reassembling contig ends and complete small contigs - all of which are likely to contain repeats.

**Comment by asl** [comment]
Reassembling just the end of the contigs does not make much sense since SPAdes tries to remove overlaps from the repeats and report the ends of repetitive contigs only once. The proper (and accurate way) is to operate on .paths / .fastg files

**Comment by splaisan** [comment]
HI I only found 3.12.0 on the SPAdes site. The assembly ended with weird messages suggesting errors!

```
circlator all \
>     --threads ${thr} \
>     raw_assembly.fasta \
>     ccs_polished_reads.fasta \
>     circlator_results
WARNING: SPAdes version 3.12.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
WARNING: SPAdes version 3.12.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
WARNING: SPAdes version 3.12.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
Traceback (most recent call last):
  File "/usr/local/bin/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/circlator/tasks/all.py", line 169, in run
    a.run()
  File "/usr/local/lib/python3.5/dist-packages/circlator/assemble.py", line 176, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/usr/local/lib/python3.5/dist-packages/circlator/assemble.py", line 145, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. Output directories are:
  /data/NC_projects/PB_Coli_8-plex/circlator_results/03.assemble.tmp.spades.97.urqwfxa7
  /data/NC_projects/PB_Coli_8-plex/circlator_results/03.assemble.tmp.spades.117.9t42jjgd
  /data/NC_projects/PB_Coli_8-plex/circlator_results/03.assemble.tmp.spades.87.rm5ify9w
  /data/NC_projects/PB_Coli_8-plex/circlator_results/03.assemble.tmp.spades.107.qnc65luw
  /data/NC_projects/PB_Coli_8-plex/circlator_results/03.assemble.tmp.spades.77.b5ilm64l
  /data/NC_projects/PB_Coli_8-plex/circlator_results/03.assemble.tmp.spades.127.uc3cflu3
The reason why should be in the spades.log file in each directory.
```

Can I use this one or should I install the old SPAdes version 3.7.1 for which I do . not find a repo for ubuntu binaries nor source code.

Thanks for help

**Comment by splaisan** [comment]
where can we get the old version of spades, I do not find it on their site. Could you possibly post it on your git as archive?
Thanks
