### ISSUE TITLE
Error running SPAdes. 

### ISSUE THREAD

**Issue by FaneeChen** [sanger-pathogens/circlator#76]
Hi

What's wrong with the SPAdes or my input files ?

Here is the input files:
circlator all polished_assembly.fasta  corrected.fasta circlator   
The polished_assemble.fasta have 48 contigs ,range from 2k to 1.7M. 

Here is the error report:
Traceback (most recent call last):
  File "/pipeline/Circlator/vir_env/bin/circlator", line 5, in <module>
    pkg_resources.run_script('circlator==1.3.1', 'circlator')
  File "/pipeline/Circlator/vir_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/pipeline/Circlator/vir_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/pipeline/Circlator/vir_env/lib/python3.5/site-packages/circlator-1.3.1-py3.5.egg/EGG-INFO/scripts/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/pipeline/Circlator/vir_env/lib/python3.5/site-packages/circlator-1.3.1-py3.5.egg/circlator/tasks/all.py", line 160, in run
    a.run()
  File "/pipeline/Circlator/vir_env/lib/python3.5/site-packages/circlator-1.3.1-py3.5.egg/circlator/assemble.py", line 123, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/pipeline/Circlator/vir_env/lib/python3.5/site-packages/circlator-1.3.1-py3.5.egg/circlator/assemble.py", line 118, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. 

Thank you for your reply!

**Comment by martinghunt** [comment]
Can you have a look in the spades log file to see why it crashed? It's called spades.log and will be somewhere in 03.assemble*/

**Comment by FaneeChen** [comment]
The path 03.assemble*/ is empty ,and I haven't found any file named as spades.log. Maybe there's something wrong when I install the  SPAdes .So I'm trying to reinstall the SPAdes now. Thanks a lot for your reply .

**Comment by jjs-16** [comment]
Hi,

**I came across a similar issue while running circlator in "all" mode. Strangely "01.mapreads.bam" file and hence "02.bam2reads.fasta" files are empty, although the run proceeds upto assemble step. Apparently there is no spades.log file as only temp files are created. Below is the log** 

circlator all --threads 8 --verbose --merge_min_id 85 --merge_breaklen 1000  contigs.fasta correctedReads.fasta.gz circ1
_________________________ Checking external programs __________________________
Circlator version: 1.5.5

External dependencies:
bwa	0.7.17	/media/jjs/Data/ngs/bwa/bwa
canu	1.8	/media/jjs/Data/ngs/canu-1.8/Linux-amd64/bin/canu
nucmer	3.1	/usr/bin/nucmer
prodigal	2.6.3	/media/jjs/Data/ngs/prodigal/Prodigal/prodigal
samtools	1.9	/usr/local/bin/samtools
spades	3.7.1	/media/jjs/Data/ngs/SPAdes-3.7.1-Linux/bin/spades.py

Python version:
3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]

Python dependencies:
openpyxl	2.5.7	/usr/local/lib/python3.5/dist-packages/openpyxl-2.5.7-py3.5.egg/openpyxl/__init__.py
pyfastaq	3.17.0	/usr/local/lib/python3.5/dist-packages/pyfastaq-3.17.0-py3.5.egg/pyfastaq/__init__.py
pymummer	0.10.3	/usr/local/lib/python3.5/dist-packages/pymummer-0.10.3-py3.5.egg/pymummer/__init__.py
pysam	0.15.1	/usr/local/lib/python3.5/dist-packages/pysam-0.15.1-py3.5-linux-x86_64.egg/pysam/__init__.py
______________________________ Running mapreads _______________________________
samtools	1.9	/usr/local/bin/samtools
bwa	0.7.17	/media/jjs/Data/ngs/bwa/bwa
syscall: bwa index -p 01.mapreads.bam.tmp.bwa_index 00.input_assembly.fasta
syscall: bwa mem -x pacbio -t 8 01.mapreads.bam.tmp.bwa_index /media/jjs/Data/5 circlator/correctedReads.fasta.gz | samtools view -F 0x0800 -T 00.input_assembly.fasta -b -o 01.mapreads.bam.tmp.unsorted.bam -
syscall: samtools sort -@ 4 -m 125M 01.mapreads.bam.tmp.unsorted.bam -o 01.mapreads.bam
syscall: samtools index 01.mapreads.bam
______________________________ Running bam2reads ______________________________
Getting reads from BAM file /media/jjs/Data/5 circlator/circ1/01.mapreads.bam
Getting all reads that map to ends of contig tig00000001. Coords: 1-50000;5205989-5255988
Getting all reads that map to ends of contig tig00000006. Coords: 1-50000;533267-583266
Getting all reads that map to ends of contig tig00000007. Coords: 1-50000;242627-292626
Getting all reads that map to contig tig00000009
Getting all reads that map to contig tig00000010
Getting all reads that map to contig tig00000011
Getting all reads that map to contig tig00000028
Getting all reads that map to contig tig00000044
Getting all unmapped reads
Finished getting reads.
Log file: /media/jjs/Data/5 circlator/circ1/02.bam2reads.log
Reads file: /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta
______________________________ Running assemble _______________________________
samtools	1.9	/usr/local/bin/samtools
spades	3.7.1	/media/jjs/Data/ngs/SPAdes-3.7.1-Linux/bin/spades.py
syscall: spades.py -s /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta -o /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.127.ko8m6aqd -t 8 -k 127 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta -o /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.117.s6bgj8_6 -t 8 -k 117 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta -o /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.107.o8x4dgia -t 8 -k 107 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta -o /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.97.f_adgrr2 -t 8 -k 97 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta -o /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.87.398pg4l5 -t 8 -k 87 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/circ1/02.bam2reads.fasta -o /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.77.y03p1__s -t 8 -k 77 --careful --only-assembler
Traceback (most recent call last):
  File "/usr/local/bin/circlator", line 4, in <module>
    __import__('pkg_resources').run_script('circlator==1.5.5', 'circlator')
  File "/home/jjs/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jjs/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/EGG-INFO/scripts/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/circlator/tasks/all.py", line 169, in run
    a.run()
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/circlator/assemble.py", line 176, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/circlator/assemble.py", line 145, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. Output directories are:
  /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.97.f_adgrr2
  /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.117.s6bgj8_6
  /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.87.398pg4l5
  /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.107.o8x4dgia
  /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.77.y03p1__s
  /media/jjs/Data/5 circlator/circ1/03.assemble.tmp.spades.127.ko8m6aqd
The reason why should be in the spades.log file in each directory.

**However, when I do the analysis step by step, "mapreads" and "bam2reads" completes successfully (with 49mb of .bam file and 9.3mb of bam3reads.fasta file) and throws an error only during assembly.
I could not troubleshoot this and would appreciate any help regarding this. Below is the log** 

$ circlator mapreads  contigs.fasta --threads 8 correctedReads.fasta.gz bwa1.bam
$ circlator bam2reads bwa1.bam bam2reads
$ circlator assemble --threads 8 --verbose bam2reads.fasta spades.assem
samtools	1.9	/usr/local/bin/samtools
spades	3.7.1	/media/jjs/Data/ngs/SPAdes-3.7.1-Linux/bin/spades.py
syscall: spades.py -s /media/jjs/Data/5 circlator/bam2reads.fasta -o /media/jjs/Data/5 circlator/spades.assem.tmp.spades.127.o8wgarb7 -t 8 -k 127 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/bam2reads.fasta -o /media/jjs/Data/5 circlator/spades.assem.tmp.spades.117.m8mh4wlv -t 8 -k 117 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/bam2reads.fasta -o /media/jjs/Data/5 circlator/spades.assem.tmp.spades.107.xk7if8rh -t 8 -k 107 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/bam2reads.fasta -o /media/jjs/Data/5 circlator/spades.assem.tmp.spades.97.7whxqif1 -t 8 -k 97 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/bam2reads.fasta -o /media/jjs/Data/5 circlator/spades.assem.tmp.spades.87.83jk8sja -t 8 -k 87 --careful --only-assembler
syscall: spades.py -s /media/jjs/Data/5 circlator/bam2reads.fasta -o /media/jjs/Data/5 circlator/spades.assem.tmp.spades.77.dq_2bwq6 -t 8 -k 77 --careful --only-assembler
Traceback (most recent call last):
  File "/usr/local/bin/circlator", line 4, in <module>
    __import__('pkg_resources').run_script('circlator==1.5.5', 'circlator')
  File "/home/jjs/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jjs/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/EGG-INFO/scripts/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/circlator/tasks/assemble.py", line 34, in run
    a.run()
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/circlator/assemble.py", line 176, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/usr/local/lib/python3.5/dist-packages/circlator-1.5.5-py3.5.egg/circlator/assemble.py", line 145, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. Output directories are:
  /media/jjs/Data/5 circlator/spades.assem.tmp.spades.97.7whxqif1
  /media/jjs/Data/5 circlator/spades.assem.tmp.spades.117.m8mh4wlv
  /media/jjs/Data/5 circlator/spades.assem.tmp.spades.87.83jk8sja
  /media/jjs/Data/5 circlator/spades.assem.tmp.spades.107.xk7if8rh
  /media/jjs/Data/5 circlator/spades.assem.tmp.spades.77.dq_2bwq6
  /media/jjs/Data/5 circlator/spades.assem.tmp.spades.127.o8wgarb7
The reason why should be in the spades.log file in each directory.
