### ISSUE TITLE
Circularization of BAC contigs

### ISSUE THREAD

**Issue by sjin09** [sanger-pathogens/circlator#79]
To whom it may concern,

I am attempting to use the circlator for circularization of BAC contigs that has been sequenced with P6C4 chemistry and assembled with CANU. The documentation suggests that corrected reads should be used as input.

We have pooled the BAC for sequencing. If we sequenced the BAC at an average depth of 100X and if there are 100 BAC clones, the coverage for the vector sequence is 10000X. The vector sequence (7507 bp) is present in all BAC clones and vector sequence hindered the assembly process and reduced the assembly statistics. Therefore, we masked the sequences aligning to the vector sequence and as a result the reads with vector sequences have not been corrected with CANU.

I wanted to ask whether the raw subreads that aligns to the vector sequences can be effectively used for the circlator.

I look forward to your response. 

Best,
Jin

**Comment by martinghunt** [comment]
Hi Jin,

Sorry, but corrected reads are needed. The reason is that circlator does a reassembly using spades. If you give it the raw pacbio reads, then the assemblies are not good enough.

Best,
Martin

**Comment by sjin09** [comment]
Thank you Martin for the quick response.

I will try to correct the vector sequence and run circlator and put it up follow it up in the issue for other people with similar issues. Or I will write another pipeline to circlarize the BAC clones.

Best,
Jin
