### ISSUE TITLE
Error running circlator with option  --assemble_not_only_assembler

### ISSUE THREAD

**Issue by svkazakov** [sanger-pathogens/circlator#80]
I ran circlator with option --assemble_not_only_assembler and got an error:

svkazakov@svkazakov /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid % circlator all --threads 6 --verbose --merge_min_length 100 --merge_min_length_merge 200 --assemble_not_only_assembler sp454Ion/scaffolds.fasta ../7P.tr.1t.fastq circSp454Ion-4 
_________________________ Checking external programs __________________________
Circlator version: 1.4.0

External dependencies:
bwa	0.7.12	/usr/bin/bwa
nucmer	3.1	/usr/bin/nucmer
prodigal	2.6.2	/usr/bin/prodigal
samtools	0.1.19	/usr/bin/samtools
spades	3.7.1	/opt/SPAdes-3.7.1/bin/spades.py

Python version:
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]

Python dependencies:
openpyxl	2.4.1	/home/svkazakov/.local/lib/python3.5/site-packages/openpyxl/__init__.py
pyfastaq	3.14.0	/home/svkazakov/.local/lib/python3.5/site-packages/pyfastaq/__init__.py
pymummer	0.10.1	/home/svkazakov/.local/lib/python3.5/site-packages/pymummer/__init__.py
pysam	0.9.1.4	/home/svkazakov/.local/lib/python3.5/site-packages/pysam/__init__.py
______________________________ Running mapreads _______________________________
samtools	0.1.19	/usr/bin/samtools
bwa	0.7.12	/usr/bin/bwa
syscall: bwa index -p 01.mapreads.bam.tmp.bwa_index 00.input_assembly.fasta
syscall: bwa mem -x pacbio -t 6 01.mapreads.bam.tmp.bwa_index /media/hdd/genome/assembly/B.pumilus_7P/new2/7P.tr.1t.fastq | samtools view -F 0x0800 -T 00.input_assembly.fasta -b -o 01.mapreads.bam.tmp.unsorted.bam -
syscall: samtools sort -@ 4 -m 125M 01.mapreads.bam.tmp.unsorted.bam  01.mapreads
syscall: samtools index 01.mapreads.bam
______________________________ Running bam2reads ______________________________
Getting reads from BAM file /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/01.mapreads.bam
Getting all reads that map to contig NODE_10_length_384_cov_25.0608_component_0
...
Getting all unmapped reads
Finished getting reads.
Log file: /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.log
Reads file: /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta
______________________________ Running assemble _______________________________
spades	3.7.1	/opt/SPAdes-3.7.1/bin/spades.py
samtools	0.1.19	/usr/bin/samtools
syscall: /opt/SPAdes-3.7.1/bin/spades.py -s /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta -o /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.127.17u586vh -t 6 -k 127 --careful
syscall: /opt/SPAdes-3.7.1/bin/spades.py -s /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta -o /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.117.gtltvt89 -t 6 -k 117 --careful
syscall: /opt/SPAdes-3.7.1/bin/spades.py -s /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta -o /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.107.y06swgpi -t 6 -k 107 --careful
syscall: /opt/SPAdes-3.7.1/bin/spades.py -s /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta -o /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.97.j0_iyhei -t 6 -k 97 --careful
syscall: /opt/SPAdes-3.7.1/bin/spades.py -s /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta -o /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.87.6eo41c9d -t 6 -k 87 --careful
syscall: /opt/SPAdes-3.7.1/bin/spades.py -s /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta -o /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.77._0rqlwyg -t 6 -k 77 --careful
Traceback (most recent call last):
  File "/home/svkazakov/.local/bin/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/home/svkazakov/.local/lib/python3.5/site-packages/circlator/tasks/all.py", line 161, in run
    a.run()
  File "/home/svkazakov/.local/lib/python3.5/site-packages/circlator/assemble.py", line 123, in run
    self.run_spades(stop_at_first_success=self.spades_use_first_success)
  File "/home/svkazakov/.local/lib/python3.5/site-packages/circlator/assemble.py", line 118, in run_spades
    raise Error('Error running SPAdes. Output directories are:\n  ' + '\n  '.join(kmer_to_dir.values()) + '\nThe reason why should be in the spades.log file in each directory.')
circlator.assemble.Error: Error running SPAdes. Output directories are:
  /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.97.j0_iyhei
  /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.117.gtltvt89
  /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.87.6eo41c9d
  /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.107.y06swgpi
  /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.77._0rqlwyg
  /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/03.assemble.tmp.spades.127.17u586vh
The reason why should be in the spades.log file in each directory.

Spades directories didn't contain any log files, but when i ran SPAdes by command specified above, i got:
== Error ==  to run read error correction, reads should be in FASTQ format (.fq, .fastq, .bam, .fq.gz, .fastq.gz, .bam.gz are supported): /media/hdd/genome/assembly/B.pumilus_7P/new2/plasmid/circSp454Ion-4/02.bam2reads.fasta (single reads, library number: 1, library type: single)

**Comment by martinghunt** [comment]
Thanks for letting me know about this. I just fixed it and did a new release 1.4.1.

Looks like you are doing this anyway, but be aware that using --assemble_not_only_assembler means that the input reads must be fastq, not fasta. This stops spades crashing.
