### ISSUE TITLE
version of SPAdes ?

### ISSUE THREAD

**Issue by gleveq1** [sanger-pathogens/circlator#85]
Why do you consider SPAdes 3.7.1 to produce the optimal results for Circlator?

We have tried it with the newest SPAdes 3.10.0 with the following warning:

WARNING: SPAdes version 3.10.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.

Thanks!

**Comment by martinghunt** [comment]
Around version 3.9.0 (I think, but would have to check) I tried all varsions from around 3.5+ on the NCTC samples from the paper. 3.7.1 gave the best results, ie most circularizations.

**Comment by gleveq1** [comment]
Thank you for the quick response;  after posting this question I saw your previous answer   (issue 72).
