### ISSUE TITLE
Circlator with short reads?

### ISSUE THREAD

**Issue by drjcthrash** [sanger-pathogens/circlator#88]
Hello,
I'm trying to verify a circularized genome. I have a single contig with what looks like overlapping ends, and I'd like to try and use circlator to finish the process, but all options appear to require long reads. I've tried doing the bwa mapping manually, but when I try to move on to the other steps, I get a series of errors. Before I go any further, can you tell me if there are any tricks to get circlator to run with short reads?

Thank you.

**Comment by martinghunt** [comment]
It was really written for long reads, so all the defaults are assuming pacbio/nanopore read length. I am guessing here so you would have to try it, but something like this:

--b2r_length_cutoff 1000 --b2r_min_read_length 30 --merge_min_length 50 --merge_min_length_merge 50 --merge_ref_end 100 --merge_reassemble_end 100

... and there may be other options that need tweaking. Essentially, make all the numbers a lot smaller!

**Comment by drjcthrash** [comment]
Ok, thank you!
